<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.0-next.9 Barbarian-transformed.glb
-->

<script>
  import { Group } from 'three'

  import { T } from '@threlte/core'
  import { useGltf, useGltfAnimations } from '@threlte/extras'

  let { fallback, error, children, ref = $bindable(), ...props } = $props()

  ref = new Group()

  const gltf = useGltf('/Barbarian-transformed.glb')

  export const { actions, mixer } = useGltfAnimations(gltf, ref)
</script>

<T
  is={ref}
  dispose={false}
  {...props}
>
  {#await gltf}
    {@render fallback?.()}
  {:then gltf}
    <T.Group name="Scene">
      <T.Group name="Rig">
        <T is={gltf.nodes.root} />
        <T.SkinnedMesh
          name="Barbarian_ArmLeft"
          geometry={gltf.nodes.Barbarian_ArmLeft.geometry}
          material={gltf.materials.barbarian_texture}
          skeleton={gltf.nodes.Barbarian_ArmLeft.skeleton}
        />
        <T.SkinnedMesh
          name="Barbarian_ArmRight"
          geometry={gltf.nodes.Barbarian_ArmRight.geometry}
          material={gltf.materials.barbarian_texture}
          skeleton={gltf.nodes.Barbarian_ArmRight.skeleton}
        />
        <T.SkinnedMesh
          name="Barbarian_Body"
          geometry={gltf.nodes.Barbarian_Body.geometry}
          material={gltf.materials.barbarian_texture}
          skeleton={gltf.nodes.Barbarian_Body.skeleton}
        />
        <T.SkinnedMesh
          name="Barbarian_Head"
          geometry={gltf.nodes.Barbarian_Head.geometry}
          material={gltf.materials.barbarian_texture}
          skeleton={gltf.nodes.Barbarian_Head.skeleton}
        />
        <T.SkinnedMesh
          name="Barbarian_LegLeft"
          geometry={gltf.nodes.Barbarian_LegLeft.geometry}
          material={gltf.materials.barbarian_texture}
          skeleton={gltf.nodes.Barbarian_LegLeft.skeleton}
        />
        <T.SkinnedMesh
          name="Barbarian_LegRight"
          geometry={gltf.nodes.Barbarian_LegRight.geometry}
          material={gltf.materials.barbarian_texture}
          skeleton={gltf.nodes.Barbarian_LegRight.skeleton}
        />
      </T.Group>
    </T.Group>
  {:catch err}
    {@render error?.({ error: err })}
  {/await}

  {@render children?.({ ref })}
</T>
